apiVersion: apps/v1
kind: Deployment
metadata:
  name: urusan-service
  labels:
    app: urusan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urusan-service
  template:
    metadata:
      labels:
        app: urusan-service
    spec:
      containers:
        - name: urusan-service
          image: urusan-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://kertaskerja-postgres:5432/kertaskerja_urusan
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
