INSERT INTO urusan (kode_urusan, nama_urusan)
VALUES ('X', 'URUSAN X.XX'),
       ('1', 'URUSAN PEMERINTAHAN WAJIB YANG BERKAITAN DENGAN PELAYANAN DASAR'),
       ('2', 'URUSAN PEMERINTAHAN WAJIB YANG TIDAK BERKAITAN DENGAN PELAYANAN DASAR'),
       ('3', 'URUSAN PEMERINTAHAN PILIHAN'),
       ('4', 'UNSUR PENDUKUNG URUSAN PEMERINTAHAN'),
       ('5', 'UNSUR PENUNJANG URUSAN PEMERINTAHAN'),
       ('6', 'UNSUR PENGAWASAN URUSAN PEMERINTAHAN'),
       ('7', 'UNSUR KEWILAYAHAN'),
       ('8', 'UNSUR PEMERINTAHAN UMUM'),
       ('9', 'UNSUR KEKHUSUSAN');